#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from config import redis_host,redis_password,redis_port,redis_db
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def EnvBool(name: str, default: bool) -> bool:  # 读取布尔类型的环境变量
    value = os.environ.get(name)
    if value is None or value.strip() == "":
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def EnvList(name: str, default: list) -> list:  # 读取逗号分隔列表类型的环境变量
    value = os.environ.get(name)
    if value is None or value.strip() == "":
        return default
    return [i.strip() for i in value.split(",") if i.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须通过环境变量 MEDUSA_SECRET_KEY 注入，保留默认值仅为避免既有部署被中断
SECRET_KEY = os.environ.get("MEDUSA_SECRET_KEY", 'wme1h&*11s!m)5fb)yjo97zt=bx^s3^$bb*18-#a!00&=k9(4o')

# SECURITY WARNING: don't run with debug turned on in production!
# 关闭 DEBUG 后 Django 不再托管静态文件，必须先执行 collectstatic 并由 Nginx 托管 /s/ 路径
# 本地开发如需调试，设置环境变量 MEDUSA_DEBUG=True 即可重新开启
DEBUG = EnvBool("MEDUSA_DEBUG", False)

# 生产环境建议通过 MEDUSA_ALLOWED_HOSTS 指定实际域名，多个域名用逗号分隔
ALLOWED_HOSTS = EnvList("MEDUSA_ALLOWED_HOSTS", ['*'])



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',#跨域用的
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Web.BasicFunctions',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',#跨域用的
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',#Csrf防护，前端需在请求头 X-CSRFToken 中携带令牌
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR+"\\Web", 'BasicFunctions')],#这边要设置绝对路才能访问到templates文件
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'Medusa.db'),
    }
}

#跨域用的
# 关闭全量放行，仅允许白名单内的前端域名；通过环境变量 MEDUSA_CORS_ORIGINS 配置，多个用逗号分隔
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = EnvList("MEDUSA_CORS_ORIGINS", [
    'http://127.0.0.1:8080',
    'http://localhost:8080',
])

CORS_ALLOW_METHODS = (
    'GET',
    'OPTIONS',
    'POST',

)

#CSRF防护相关配置
# 前端与API同域部署（Nginx 反代 /api），Lax 策略即可正常携带 Cookie
CSRF_COOKIE_NAME = 'medusax_csrftoken'
# WSGI 会将请求头统一转为大写并把 '-' 替换为 '_'，故前端发送 X-CSRFToken 即可命中该键
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_HTTPONLY = False  # 必须为 False，前端需要读取该 Cookie 并回传至请求头
CSRF_COOKIE_SAMESITE = os.environ.get("MEDUSA_CSRF_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = EnvBool("MEDUSA_CSRF_SECURE", False)  # 全站 HTTPS 时建议设为 True
CSRF_USE_SESSIONS = False
# 校验失败时返回JSON而非HTML页面，前端据此自动重新获取令牌并重试
CSRF_FAILURE_VIEW = 'Web.BasicFunctions.CsrfToken.CsrfFailure'

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'token',
    'x-requested-with',
    'Pragma',
    'TrojanGenerateFileName',
    'TrojanId',
    'Key',
    'FileFullPath',
    'UUID',
)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/s/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'Web/Image'),#静态资源加载位置
    os.path.join(BASE_DIR,'Web/CrossSiteScriptHub/CrossSiteScriptProject'),#存放XSSjs文件目录
)
# 关闭 DEBUG 后由 collectstatic 汇总到该目录，再由 Nginx 直接托管 /s/ 路径，不再走 Django
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


#celery
CELERY_RESULT_BACKEND='redis://:'+redis_password+'@'+redis_host+':'+redis_port+'/'+redis_db
CELERY_BROKER_URL='redis://:'+redis_password+'@'+redis_host+':'+redis_port+'/'+redis_db
'''

CELERY_RESULT_BACKEND='redis://:password@host:port/db'
host: Redis的服务器的名称或IP地址。例如 localhost:本地主机。
port: Redis的服务器。默认值是6379
db: 使用的数据库数,默认值为0
password: 密码用于连接到数据库。

缓存后端设置
使用单个memcached服务器：
CELERY_RESULT_BACKEND='cache+memcached://127.0.0.1:11211/'
cache : 缓存
'''
CELERY_ACCEPT_CONTENT=['json']
CELERY_TASK_SERIALIZER='json'


#上传图片最大值设置
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485761